/**:
  ros__parameters:
    rate: 100.0
    x0: -0.5
    y0: 0.7
    theta0: 1.28
    arena_x_length: 20.0
    arena_y_length: 20.0
    obstacles/x: [-0.5, 0.8, 0.4]
    obstacles/y: [-0.7, -0.8, 0.8]
    obstacles/r: 0.038
    input_noice: 0.0 #0.1
    slip_fraction: 0.0 #0.1
    basic_sensor_variance: 0.0 #1e-4
    max_range: 3.5